name: Deploy to Staging

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-staging:
    if: |
      github.event_name == 'workflow_run' && 
      github.event.workflow_run.conclusion == 'success' || 
      (github.event_name == 'release' && !github.event.release.prerelease)
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ steps.deploy.outputs.deployment_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          preview: true

      - name: Generate staging tag
        id: tag
        run: |
          DATE=$(date +'%Y%m%d')
          COUNT=$(git tag -l "staging-$DATE-*" | wc -l)
          NEW_COUNT=$((COUNT + 1))
          TAG="staging-$DATE-$NEW_COUNT"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag $TAG
          git push origin $TAG

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Staging Release ${{ steps.tag.outputs.tag }}
          body: |
            Automatic staging release
            Deployed to: ${{ steps.deploy.outputs.deployment_url }}
          draft: false
          prerelease: true 